/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                "aqua-primary": "#0077B6",
                "aqua-primary-hover": "#005F8F",
                "aqua-secondary": "#48CAE4",
                "aqua-success": "#2DC653",
                "aqua-warning": "#F4A261",
                "aqua-danger": "#E63946",
                "aqua-background": "#F8FCFD",
                "aqua-surface": "#FFFFFF",
                "aqua-text": "#023047",
                "aqua-text-muted": "#64748B",
                "risk-low": "#2DC653",
                "risk-moderate": "#F4A261",
                "risk-high": "#F07A3C",
                "risk-veryhigh": "#E63946",
                "tertiary-fixed": "#c8ecf6",
                "outline": "#64748B",
                "inverse-surface": "#023047",
                "surface-bright": "#F8FCFD",
                "on-error": "#ffffff",
                "background": "#F8FCFD",
                "on-tertiary-fixed-variant": "#014f70",
                "surface-dim": "#dbe7ec",
                "surface-container-highest": "#e1eef3",
                "surface-container-low": "#eef8fb",
                "inverse-primary": "#90e0ef",
                "on-surface-variant": "#64748B",
                "on-primary": "#ffffff",
                "primary-fixed": "#ade8f4",
                "secondary-fixed": "#caf0f8",
                "secondary": "#0096c7",
                "on-primary-container": "#013a52",
                "error": "#E63946",
                "on-tertiary": "#023047",
                "tertiary-fixed-dim": "#90e0ef",
                "primary-fixed-dim": "#48CAE4",
                "surface-container-lowest": "#ffffff",
                "surface-variant": "#e1eef3",
                "on-primary-fixed": "#013a52",
                "secondary-fixed-dim": "#90e0ef",
                "surface-container-high": "#e9f5f9",
                "secondary-container": "#caf0f8",
                "primary": "#0077B6",
                "on-background": "#023047",
                "tertiary": "#2DC653",
                "outline-variant": "#c3d5db",
                "on-surface": "#023047",
                "on-error-container": "#93000a",
                "surface": "#F8FCFD",
                "primary-container": "#48CAE4",
                "inverse-on-surface": "#f2fafd",
                "on-tertiary-container": "#0d3d1c",
                "on-secondary-fixed": "#013a52",
                "on-secondary-container": "#014f70",
                "on-secondary-fixed-variant": "#013a52",
                "surface-container": "#eef8fb",
                "tertiary-container": "#b8f3c8",
                "on-primary-fixed-variant": "#005F8F",
                "on-tertiary-fixed": "#0d3d1c",
                "on-secondary": "#ffffff",
                "surface-tint": "#0077B6",
                "error-container": "#ffdad6"
            },
            borderRadius: {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            spacing: {
                "margin": "20px",
                "xs": "4px",
                "md": "24px",
                "xl": "64px",
                "sm": "12px",
                "gutter": "16px",
                "base": "8px",
                "lg": "40px"
            },
            fontFamily: {
                "body-lg": ["'Plus Jakarta Sans'", "sans-serif"],
                "label-sm": ["'Plus Jakarta Sans'", "sans-serif"],
                "headline-md": ["'Plus Jakarta Sans'", "sans-serif"],
                "body-md": ["'Plus Jakarta Sans'", "sans-serif"],
                "label-lg": ["'Plus Jakarta Sans'", "sans-serif"],
                "headline-lg": ["'Plus Jakarta Sans'", "sans-serif"]
            },
            fontSize: {
                "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
                "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
                "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
                "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
                "label-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "600" }],
                "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }]
            }
        },
    },
}
